### PR TITLE
Feature/event hub trigger unit tests

### PR DESCRIPTION
**Pull request by FrancisLandrian**
Adding Unit Tests for the Event Hub Trigger Function methods. Also added a constructor for the SystemProperty class to have cleaner instantiations of the class.

### CODE REVIEW

**Comment by kaibocai** [comment]
Hi @FrancisLandrian , thanks for you contribution, but I wonder why unit tests are added to samples instead of https://github.com/Azure/azure-functions-java-worker

**Comment by FrancisLandrian** [comment]
Hello @kaibocai. I added these unit tests (and later I want to add more) for these samples since Java Azure Function developers will likely visit this repo, as I did, and will eventually have to write tests. The unit tests are meant to help devs understand how to test Java Azure Functions. I was not aware of the URL you provided until I spoke to Shreyas.

Also, the EventHubTriggerTests.java file in the URL you provided does not seem to have any actual tests. The code in the other files is C# as well, and not Java. It is your call, however, where you would like to store these tests. I think it logically makes sense to place them here, since the core Java functionality is in this repo, and the accompanying tests which I wrote match them.

**Comment by kaibocai** [comment]
> Hello @kaibocai. I added these unit tests (and later I want to add more) for these samples since Java Azure Function developers will likely visit this repo, as I did, and will eventually have to write tests. The unit tests are meant to help devs understand how to test Java Azure Functions. I was not aware of the URL you provided until I spoke to Shreyas.
> 
> Also, the EventHubTriggerTests.java file in the URL you provided does not seem to have any actual tests. The code in the other files is C# as well, and not Java. It is your call, however, where you would like to store these tests. I think it logically makes sense to place them here, since the core Java functionality is in this repo, and the accompanying tests which I wrote match them

**Review by kaibocai — APPROVED** [review]
LGTM

**Review by shreyas-gopalakrishna — APPROVED** [review]

**Pull request merged**
